deployScripts:
  start:
    - npm install -g cnpm --registry=https://registry.npm.taobao.org
    - cnpm install
    - cnpm run start
  delete:
    - npm run stop
  restart:
    - cnpm install
    - cnpm run restart